### ISSUE TITLE
Doesn’t follow the recommended Mill project structure

### ISSUE THREAD

**Issue by asarkar** [alvinj/ScalaMillHelloWorld#1]
This project doesn’t seem to follow the recommended Mill project structure, which is surprisingly difficult and frustrating to find. If the structure isn’t as expected, IntelliJ won’t recognize the project, and one is left with nothing but a bunch of text files.

The [mill-scala-hello Gitter template](https://github.com/com-lihaoyi/mill-scala-hello.g8) generates the following project structure.

```
foo
├── build.sc
└── foo
    ├── src
    │   └── com
    │       └── example
    │           └── Hello.scala
    └── test
        └── src
            └── com
                └── example
                    └── HelloTest.scala
```
Although the top-level directory and the only Mill module are both named `foo`, it appears that this isn’t a requirement, and the top-level `foo` may contain multiple Mill modules named whatever necessary.

The package is under the `src` directories, and is `com.example` above.

**Comment by alvinj** [comment]
Thanks for this, I appreciate it.

I haven’t used Mill much lately, but I wrote about having multiple modules in subdirectories [at this link](https://alvinalexander.com/scala/mill-build-tool/step-1-hello-world/). There I created the directories like this:

```sh
mkdir -p HelloWorld/src/main/scala
```

but frankly, I don’t remember if that was a “standard” at that time or something I carried over from SBT.

On [this page](https://alvinalexander.com/scala/mill-build-tool/unit-testing-scalatest-dependencies/) I showed a reason for having `src/main` as a root directory (but again, that was three years ago, and I don’t remember what was considered standard or a best practice at that time). But a key to that approach was having the `resources` folder for project resources.

I do think that Mill is flexible, and you can have that `resources` folder in almost any location, but that’s what I went with at that time.

**Comment by asarkar** [comment]
Since creating this ticket, I realized that Mill doesn’t have a recommended project structure. Each of the resources/persons puts their own spin on it. See this [Reddit question](https://www.reddit.com/r/scala/comments/18db51p/mill_project_structure/) I had posted.

**Comment by alvinj** [comment]
Yeah ... I don’t know why there isn’t a standard. A great thing about SBT, Maven, and similar tools is that you can go from one project to another, and know on Day 1 where things are. Even if there isn’t a standard, a “recommended” solution like you mention on Reddit would be good.

**Comment by alvinj** [comment]
I can’t really help with this, so I’m going to close this issue.
